### PR TITLE
ability to insert a feature

### PR DESCRIPTION
**Pull request by steveoh**

### CODE REVIEW

**Comment by stdavis** [comment]
Are these really not valid actions for terrestrial treatment areas?
image

**Comment by steveoh** [comment]
that is a [bug](https://github.com/agrc/wri-webapi/pull/3/files#diff-1e21503c204f3866a58261779cb8c9e7R30). let me move that code into point and line only.

**Comment by stdavis** [comment]
I got this error message
image

With these inputs:
image

**Comment by steveoh** [comment]
@stdavis paste a screenshot of the sql column schema for `areaherbicide`.

I can't reproduce this.

**Comment by stdavis** [comment]
image

**Comment by steveoh** [comment]
HerbicideDescription should be a nvarchar(255)

**Comment by stdavis** [comment]
OK. I've updated the field type, pulled your latest commit and rebuilt.

Now I get "Error in handling operation ExtractIntersections" when trying to post the same data.

**Comment by stdavis** [comment]
What about this one?
image

**Comment by stdavis** [comment]
This seems to be working to me. Except for the one time that I got the "Error in Handling operation ExtractionIntersections". I've submitted a bunch more features successfully. I'm good to :shipit:

**Comment by stdavis** [comment]
Except for the weird area calcs. ;)

**Pull request merged**
